<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FrenteCaixa.Estoque.Application\FrenteCaixa.Estoque.Application.csproj" />
    <ProjectReference Include="..\FrenteCaixa.Estoque.Domain\FrenteCaixa.Estoque.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\building-blocks\FrenteCaixa.BuildingBlocks\FrenteCaixa.BuildingBlocks.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
