<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FrenteCaixa.Pagamentos.Application\FrenteCaixa.Pagamentos.Application.csproj" />
    <ProjectReference Include="..\FrenteCaixa.Pagamentos.Domain\FrenteCaixa.Pagamentos.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\building-blocks\FrenteCaixa.BuildingBlocks\FrenteCaixa.BuildingBlocks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
