// <auto-generated />
using System;
using FrenteCaixa.Relatorios.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FrenteCaixa.Relatorios.Infrastructure.Migrations
{
    [DbContext(typeof(RelatoriosDbContext))]
    [Migration("20260717131934_RelatoriosVendasConcluidas")]
    partial class RelatoriosVendasConcluidas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FrenteCaixa.BuildingBlocks.Inbox.RegistroInbox", b =>
                {
                    b.Property<Guid>("MensagemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConsumidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("MensagemId");

                    b.HasIndex("RoutingKey");

                    b.ToTable("inbox_mensagens", (string)null);
                });

            modelBuilder.Entity("FrenteCaixa.Relatorios.Domain.Relatorios.ItemVendaConcluidaProjetada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("itens_vendas_concluidas", (string)null);
                });

            modelBuilder.Entity("FrenteCaixa.Relatorios.Domain.Relatorios.VendaConcluidaProjetada", b =>
                {
                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaixaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PagamentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProjetadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("VendaId");

                    b.HasIndex("ConcluidaEm");

                    b.HasIndex("FormaPagamento");

                    b.ToTable("vendas_concluidas", (string)null);
                });

            modelBuilder.Entity("FrenteCaixa.Relatorios.Domain.Relatorios.ItemVendaConcluidaProjetada", b =>
                {
                    b.HasOne("FrenteCaixa.Relatorios.Domain.Relatorios.VendaConcluidaProjetada", null)
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FrenteCaixa.Relatorios.Domain.Relatorios.VendaConcluidaProjetada", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
